'use strict';

const SUPABASE_URL = 'https://rxwsgaeaalmbnejabbfu.supabase.co';
const SUPABASE_KEY = 'sb_publishable_TBQT9HzDLFDsYTc7O-_Fqw_KUr2sgk6';
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const $ = id => document.getElementById(id);
const money = x => '$' + Number(x || 0).toFixed(2);
const egp = x => Number(x || 0).toLocaleString(undefined, { maximumFractionDigits: 2 }) + ' EGP';
const tiers = [{q:5,f:20},{q:10,f:35},{q:20,f:65},{q:25,f:85},{q:30,f:100}];
let rate=0, override=false, box=false, items=[], editIndex=null, alloc=[], user=null, cloudCigars=[], cloudOrders=[];
let local = JSON.parse(localStorage.getItem('cigarCalcDraftV2') || '{"cigars":[],"orders":[]}');
const saveLocal=()=>localStorage.setItem('cigarCalcDraftV2',JSON.stringify(local));
function fee(q){if(!q)return 0;const t=tiers.find(x=>q<=x.q)||tiers[tiers.length-1];return t.f/t.q*q}
function calc(){const q=+($('qty').value||0),p=+($('price').value||0),tax=p*.07,f=fee(q),b=box?5:0,u=p+tax+f+b,total=u*rate,per=q?total/q:0;$('orig').textContent=money(p);$('tax').textContent=money(tax);$('fee').textContent=money(f);$('box').textContent=money(b);$('total').textContent=egp(total);return{q,p,tax,f,b,u,total,per}}
function norm(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function similarity(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;const A=new Set(a.split(' ')),B=new Set(b.split(' '));return [...A].filter(x=>B.has(x)).length/Math.max(A.size,B.size)}
function allCigars(){return user?cloudCigars:local.cigars}
function findCigar(q){return allCigars().map(c=>({...c,s:similarity(q,c.name)})).filter(c=>c.s>=.25).sort((a,b)=>b.s-a.s).slice(0,6)}
function showSuggestions(){const q=$('cigar').value.trim(),el=$('suggest');if(!q){el.classList.add('hidden');return}const found=findCigar(q);el.innerHTML=found.length?found.map(c=>`<div data-id="${c.id}"><b>${c.name}</b><span class="muted">${c.vitola?' · '+c.vitola:''}</span></div>`).join(''):'<div><b>New cigar</b><span class="muted">No saved match — it will be learned when added.</span></div>';el.classList.remove('hidden');el.querySelectorAll('[data-id]').forEach(d=>d.onclick=()=>{const c=allCigars().find(x=>x.id===d.dataset.id);$('cigar').value=c.name;if(c.vitola&&!$('vitola').value)$('vitola').value=c.vitola;el.classList.add('hidden');showPriceHistory()})}
function historiesFor(c,v){return (c.history||[]).filter(x=>!v||norm(x.vitola)===norm(v)).sort((a,b)=>new Date(b.date||b.purchased_at)-new Date(a.date||a.purchased_at))}
function showPriceHistory(){const n=$('cigar').value.trim(),v=$('vitola').value.trim(),el=$('priceHistory');if(!n){el.innerHTML='';return}const c=allCigars().find(x=>norm(x.name)===norm(n));if(!c){el.innerHTML='<div class="history"><span class="badge neutral">NEW ITEM</span><div class="muted" style="margin-top:5px">No previous price history.</div></div>';return}const h=historiesFor(c,v).slice(0,5);if(!h.length){el.innerHTML='<div class="history"><span class="badge neutral">NO HISTORY FOR THIS VITOLA</span></div>';return}const cur=calc().per,prev=+h[0].price,avg=h.reduce((s,x)=>s+(+x.price||0),0)/h.length,best=Math.min(...h.map(x=>+x.price||0)),pct=prev?((cur-prev)/prev*100):0,cls=cur<=avg*.95?'good':cur<=avg*1.05?'warn':'bad',txt=cur<=avg*.95?'GOOD PRICE':cur<=avg*1.05?'AROUND AVERAGE':'HIGHER THAN USUAL';el.innerHTML=`<div class="history"><div style="display:flex;justify-content:space-between;gap:8px"><b>${c.name}${v?' · '+v:''}</b><span class="badge ${cls}">${txt}</span></div><div style="margin-top:7px"><b>${egp(cur)}/stick</b> <span class="muted">· previous ${egp(prev)} · average ${egp(avg)} · best ${egp(best)}</span></div>${pct?`<div class="muted" style="font-size:12px;margin-top:3px">${pct<0?'↓':'↑'} ${Math.abs(pct).toFixed(1)}% vs previous</div>`:''}</div>`}
function allocationUI(){const el=$('allocList');el.innerHTML=alloc.map((x,i)=>`<div class="allocItem"><div><label>Cigar</label><input data-i="${i}" data-k="name" value="${x.name||''}" placeholder="Cigar"></div><div><label>Vitola</label><input data-i="${i}" data-k="vitola" value="${x.vitola||''}" placeholder="Size"></div><div><label>Qty</label><input type="number" min="1" data-i="${i}" data-k="qty" value="${x.qty||1}"></div><div><label>Price/stick EGP</label><input type="number" min="0" step=".01" data-i="${i}" data-k="price" value="${x.price??''}" placeholder="Manual"></div><button class="btn del" data-del="${i}">×</button></div>`).join('');el.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{alloc[+i.dataset.i][i.dataset.k]=(i.dataset.k==='name'||i.dataset.k==='vitola')?i.value:+i.value;allocSummary()}));el.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{alloc.splice(+b.dataset.del,1);allocationUI()}));allocSummary()}
function allocSummary(){const el=$('allocSummary');if(!alloc.length){el.classList.add('hidden');return}el.classList.remove('hidden');const c=calc(),aq=alloc.reduce((s,a)=>s+(+a.qty||0),0),at=alloc.reduce((s,a)=>s+(+a.qty||0)*(+a.price||0),0),d=c.total-at;el.innerHTML=`<div class="allocTotal"><span>Allocated: <b>${egp(at)}</b> · ${aq} sticks</span><span class="${Math.abs(d)<.01?'ok':'error'}">${Math.abs(d)<.01?'✓ Fully allocated':'Difference: '+egp(d)}</span></div>`}
function addAllocation(){const c=calc();alloc.push({name:$('cigar').value.trim(),vitola:$('vitola').value.trim(),qty:alloc.length?1:c.q,price:alloc.length?0:c.per});allocationUI()}
async function ensureCloudCigar(name,vitola){const nn=norm(name),key=nn+'|'+norm(vitola||'');let c=cloudCigars.find(x=>x.normalized_key===key);if(c)return c;const {data,error}=await sb.from('cigars').upsert({user_id:user.id,name:name,normalized_name:nn,normalized_key:key,vitola:vitola||''},{onConflict:'user_id,normalized_key'}).select().single();if(error)throw error;c={...data,history:[]};cloudCigars.push(c);return c}
async function saveCloudOrder(){if(!user)throw new Error('Please log in first.');if(!items.length)throw new Error('Add at least one item first.');const total=items.reduce((s,x)=>s+x.total,0),q=items.reduce((s,x)=>s+x.q,0),o={user_id:user.id,total_cigars:q,total_egp:total,average_per_stick_egp:q?total/q:0,usdt_egp_rate:items[0].rate,rate_source:items[0].rateSource,original_usd_total:items.reduce((s,x)=>s+x.p,0),tax_usd:items.reduce((s,x)=>s+x.tax,0),quantity_fees_usd:items.reduce((s,x)=>s+x.f,0),box_fees_usd:items.reduce((s,x)=>s+x.b,0)};const {data:od,error:oe}=await sb.from('orders').insert(o).select().single();if(oe)throw oe;const rows=[];const ph=[];for(const it of items){const rs=it.alloc?.length?it.alloc:[{name:it.cigar,vitola:it.vitola,qty:it.q,price:it.per,mode:'automatic'}];for(const a of rs){if(!a.name)continue;const c=await ensureCloudCigar(a.name,a.vitola);const mode=it.alloc?.length?'manual':'automatic';rows.push({order_id:od.id,user_id:user.id,cigar_id:c.id,cigar_name_snapshot:a.name,vitola_snapshot:a.vitola||'',quantity:+a.qty||1,price_per_stick_egp:+a.price||0,allocation_mode:mode});ph.push({user_id:user.id,cigar_id:c.id,order_id:od.id,purchased_at:od.created_at,quantity:+a.qty||1,price_per_stick_egp:+a.price||0,order_total_egp:it.total,usdt_egp_rate:it.rate,rate_source:it.rateSource});}}if(rows.length){const {error:e1}=await sb.from('order_items').insert(rows);if(e1)throw e1;const {error:e2}=await sb.from('cigar_price_history').insert(ph);if(e2)throw e2}await loadCloud();return od}
async function loadCloud(){if(!user)return;const {data:cs,error:ce}=await sb.from('cigars').select('*').order('name');if(ce)throw ce;const {data:hs,error:he}=await sb.from('cigar_price_history').select('*').order('purchased_at',{ascending:false});if(he)throw he;cloudCigars=(cs||[]).map(c=>({...c,history:(hs||[]).filter(h=>h.cigar_id===c.id).map(h=>({date:h.purchased_at,vitola:h.vitola_snapshot||c.vitola,price:h.price_per_stick_egp,qty:h.quantity,rate:h.usdt_egp_rate,rateSource:h.rate_source}))}));const {data:os,error:oe}=await sb.from('orders').select('*').order('created_at',{ascending:false});if(oe)throw oe;const {data:is,error:ie}=await sb.from('order_items').select('*').order('created_at');if(ie)throw ie;cloudOrders=(os||[]).map(o=>({...o,items:(is||[]).filter(i=>i.order_id===o.id)}));renderHistory();renderDB();showPriceHistory()}
function renderItems(){const el=$('items');if(!items.length)el.innerHTML='<div class="muted" style="text-align:center;padding:18px">No items added yet.</div>';else el.innerHTML=items.map((x,i)=>`<div class="item"><div><b>${x.label}</b><div class="meta">${x.alloc?.length?x.alloc.map(a=>`${a.name||'Unnamed'} · ${a.vitola||'No size'} × ${a.qty} @ ${egp(a.price)}`).join('<br>'):`Original ${money(x.p)} · Tax ${money(x.tax)} · Fee ${money(x.f)} · Box ${money(x.b)}`}</div><div class="meta">Rate: ${x.rate.toFixed(2)} EGP/USDT · ${x.rateSource==='manual'?'Manual':'Live'}</div></div><div class="right"><strong>${egp(x.total)}</strong><div class="buttons"><button class="btn small" data-edit="${i}">Edit</button><button class="btn small del" data-delete="${i}">Delete</button></div></div></div>`).join('');el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editItem(+b.dataset.edit));el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.delete,1);renderItems()});const q=items.reduce((s,x)=>s+x.q,0),t=items.reduce((s,x)=>s+x.total,0);$('gq').textContent=q;$('gt').textContent=egp(t);$('gp').textContent=egp(q?t/q:0)}
function editItem(i){const x=items[i];editIndex=i;$('qty').value=x.q;$('price').value=x.p;box=x.box;$('yes').classList.toggle('active',box);$('no').classList.toggle('active',!box);$('cigar').value=x.cigar||'';$('vitola').value=x.vitola||'';alloc=JSON.parse(JSON.stringify(x.alloc||[]));allocationUI();$('add').textContent='✓ Update item';calc();scrollTo({top:0,behavior:'smooth'})}
function addItem(){const x=calc();if(!x.q||!x.p)return alert('Enter both the number of cigars and original cigar price.');if(alloc.length){const aq=alloc.reduce((s,a)=>s+(+a.qty||0),0),at=alloc.reduce((s,a)=>s+(+a.qty||0)*(+a.price||0),0);if(aq!==x.q)return alert('Allocation quantities must equal the order quantity.');if(Math.abs(at-x.total)>1)return alert('Allocation total must equal the calculated order total. Adjust the individual prices/stick.')}const item={...x,box,cigar:$('cigar').value.trim(),vitola:$('vitola').value.trim(),alloc:alloc.length?JSON.parse(JSON.stringify(alloc)):null,rate,rateSource:override?'manual':'live',label:alloc.length?'Mixed / Custom allocation':($('cigar').value.trim()?$('cigar').value.trim()+($('vitola').value.trim()?' · '+$('vitola').value.trim():''):x.q+' cigars')};if(editIndex!==null){items[editIndex]=item;editIndex=null;$('add').textContent='＋ Add to order'}else items.push(item);renderItems();alloc=[];allocationUI();$('qty').value='';$('price').value='';$('cigar').value='';$('vitola').value='';box=false;$('no').classList.add('active');$('yes').classList.remove('active');calc();showPriceHistory()}
function renderHistory(){const el=$('hist'),orders=user?cloudOrders:local.orders;if(!orders.length){el.innerHTML='<div class="muted" style="padding:20px;text-align:center">No saved orders yet.</div>';return}el.innerHTML=orders.map((o,i)=>{const total=+o.total_egp||+o.total||0,q=+o.total_cigars||+o.q||0,r=+o.usdt_egp_rate||+(o.items?.[0]?.rate||0),src=o.rate_source||o.items?.[0]?.rateSource||'live',rows=o.items||[];return`<div class="historyCard"><div class="historyHead"><div><b>Order ${orders.length-i}</b><div class="pill">${new Date(o.created_at||o.date).toLocaleString()} · ${q} cigars</div></div><b>${egp(total)}</b></div><div class="meta" style="margin-top:8px"><b>USDT/EGP rate: ${r?r.toFixed(2):'—'} EGP/USDT</b> · ${src==='manual'?'Manual rate':'Live rate'}<br>${rows.map(x=>`${x.cigar_name_snapshot||x.label||''}${x.vitola_snapshot?' · '+x.vitola_snapshot:''} — ${x.quantity||x.q||''} × ${egp(x.price_per_stick_egp||x.per||0)}`).join('<br>')}</div></div>`}).join('')}
function renderDB(){const el=$('db'),cs=user?cloudCigars:local.cigars;if(!cs.length){el.innerHTML='<div class="muted" style="padding:20px;text-align:center">Your cigar database will build automatically as you save purchases.</div>';return}el.innerHTML='<input class="dbSearch" id="dbSearch" placeholder="Search saved cigars…">'+cs.map(c=>{const h=c.history||[],avg=h.length?h.reduce((s,x)=>s+(+x.price||0),0)/h.length:0,best=h.length?Math.min(...h.map(x=>+x.price||0)):0,last=h.length?+h[0].price:0,rateText=h.length&&h[0].rate?` · Last rate ${(+h[0].rate).toFixed(2)}`:'';return`<div class="dbRow"><b>${c.name}</b><div class="dbStats">${c.vitola||c.vitolas?.join(', ')||'No vitola saved'} · ${h.length} purchases · Last ${egp(last)} · Avg ${egp(avg)} · Best ${egp(best)}${rateText}</div></div>`}).join('');$('dbSearch').oninput=e=>{const q=norm(e.target.value);el.querySelectorAll('.dbRow').forEach(r=>r.style.display=!q||norm(r.textContent).includes(q)?'block':'none')};}
function tab(which){['current','hist','db'].forEach(x=>$(x).classList.toggle('hidden',x!==which));['orderTab','historyTab','dbTab'].forEach(x=>$(x).classList.remove('active'));$(which==='current'?'orderTab':which==='hist'?'historyTab':'dbTab').classList.add('active');if(which==='hist')renderHistory();if(which==='db')renderDB()}
function authUI(){const s=$('authStatus');if(user){s.innerHTML=`<small>☁ Synced: ${user.email}</small><button class="btn small" id="logout">Log out</button>`;$('authBox').classList.add('hidden');$('logout').onclick=async()=>{await sb.auth.signOut()}}else{s.innerHTML='<small>☁ Local mode</small><button class="btn small" id="showLogin">Cloud login</button>';$('authBox').classList.add('hidden');$('showLogin').onclick=()=>{ $('authBox').classList.remove('hidden');$('email').focus() }} }
$('signup').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6)return $('authMsg').textContent='Enter an email and a password of at least 6 characters.';const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});$('authMsg').textContent=error?error.message:(data.session?'Account created and logged in.':'Account created. Check your email to confirm it, then log in.')};
$('login').onclick=async()=>{const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return $('authMsg').textContent=error.message;user=data.user;authUI();try{await loadCloud()}catch(e){alert('Logged in, but cloud data could not be loaded: '+e.message)}};
$('qty').oninput=()=>{calc();showPriceHistory();allocSummary()};$('price').oninput=()=>{calc();showPriceHistory();allocSummary()};$('cigar').oninput=()=>{showSuggestions();showPriceHistory()};$('vitola').oninput=showPriceHistory;$('customBtn').onclick=addAllocation;$('add').onclick=addItem;$('no').onclick=()=>{box=false;$('no').classList.add('active');$('yes').classList.remove('active');calc();showPriceHistory()};$('yes').onclick=()=>{box=true;$('yes').classList.add('active');$('no').classList.remove('active');calc();showPriceHistory()};$('orderTab').onclick=()=>tab('current');$('historyTab').onclick=()=>tab('hist');$('dbTab').onclick=()=>tab('db');$('ovBtn').onclick=()=>$('ov').classList.toggle('hidden');$('apply').onclick=()=>{const x=+$('manual').value;if(x>0){rate=x;override=true;$('rate').textContent=x.toFixed(2);$('status').textContent='Manual rate';calc();showPriceHistory()}};$('live').onclick=()=>{override=false;fetchRate()};
async function fetchRate(){try{const r=await fetch('/api/rate',{cache:'no-store'});if(!r.ok)throw new Error('rate endpoint');const d=await r.json(),x=+d.buy;if(!x)throw new Error('bad rate');if(!override)rate=x;$('rate').textContent=rate.toFixed(2);$('status').textContent='Live Binance P2P BUY · '+new Date(d.updatedAt||Date.now()).toLocaleTimeString();calc();showPriceHistory()}catch(e){$('status').textContent='Live rate unavailable — use Override rate'}}
$('saveOrder').onclick=async()=>{if(!items.length)return alert('Add at least one item first.');if(!user){$('authBox').classList.remove('hidden');return alert('Log in to save orders to your cloud database.')}try{await saveCloudOrder();items=[];renderItems();alert('Order saved to Supabase history.')}catch(e){alert('Could not save order: '+e.message)}};
sb.auth.onAuthStateChange(async(_event,session)=>{user=session?.user||null;authUI();if(user){try{await loadCloud()}catch(e){console.error(e)}}else{cloudCigars=[];cloudOrders=[];renderHistory();renderDB()}});
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('install').style.display='block'});$('installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else if(/iphone|ipad|ipod/i.test(navigator.userAgent))alert('On iPhone: Share → Add to Home Screen.');else alert('Use the browser menu and choose Install app / Add to Home Screen.')};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
fetchRate();setInterval(()=>{if(!override)fetchRate()},60000);renderItems();allocationUI();authUI();