'use strict';
(function(){
const num=v=>Number(v||0);
const money=v=>num(v).toFixed(2);
const cell=v=>{const s=String(v??'');return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};
const csv=rows=>'\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n');
const dl=(name,text,type)=>{const b=new Blob([text],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};
const stamp=()=>new Date().toISOString().slice(0,10);
const current=()=>{try{return Array.isArray(items)?items:[]}catch(e){return[]}};
const orders=()=>{try{return user&&Array.isArray(cloudOrders)?cloudOrders:(local?.orders||[])}catch(e){return[]}};
const orderPics=o=>Array.from(new Set([...(Array.isArray(o?.order_image_urls)?o.order_image_urls:[]),o?.order_image_url].filter(Boolean)));
const itemRows=o=>o?.items||[];
const itemName=x=>x?.cigar_name_snapshot||x?.cigar||x?.name||x?.label||'Unnamed item';
const itemQty=x=>num(x?.quantity??x?.qty);
const itemPrice=x=>num(x?.price_per_stick_egp??x?.price??x?.per);
const imgUrls=x=>Array.from(new Set([...(Array.isArray(x?.image_urls)?x.image_urls:[]),x?.image_url].filter(Boolean)));
async function fileData(file){if(!file)return '';return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(file)})}
async function remoteData(url){if(!url)return '';if(String(url).startsWith('data:'))return String(url);try{const r=await fetch(url,{mode:'cors'});if(!r.ok)throw new Error('fetch');return await fileData(await r.blob())}catch(e){return url||''}}
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
async function makeReport(title,meta,list){let body='';for(const o of list){const pics=orderPics(o);body+='<section class="order"><h2>'+esc(o.title||'Order')+'</h2><div class="meta">'+esc(meta(o))+'</div>';if(pics.length){body+='<h3>Whole order pictures</h3><div class="photos">';for(const u of pics)body+='<img src="'+esc(await remoteData(u))+'">';body+='</div>'}body+='<table><thead><tr><th>Pictures</th><th>Cigar / Item</th><th>Vitola</th><th>Qty</th><th>Price/stick EGP</th></tr></thead><tbody>';for(const x of itemRows(o)){let urls=imgUrls(x);const files=Array.isArray(x._imageFiles)?x._imageFiles:(x._imageFile?[x._imageFile]:[]);for(const f of files)urls.push(await fileData(f));urls=Array.from(new Set(urls));const picsHtml=urls.length?'<div class="itempics">'+(await Promise.all(urls.map(async u=>'<img class="itempic" src="'+esc(await remoteData(u))+'">'))).join('')+'</div>':'—';body+='<tr><td>'+picsHtml+'</td><td>'+esc(itemName(x))+'</td><td>'+esc(x.vitola_snapshot||x.vitola||'')+'</td><td>'+itemQty(x)+'</td><td>'+money(itemPrice(x))+'</td></tr>'}body+='</tbody></table></section>'}return '<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>body{font-family:Arial;margin:28px;color:#222}.order{border:1px solid #ccc;border-radius:12px;padding:18px;margin-bottom:22px;page-break-inside:avoid}.meta{color:#555;margin-bottom:12px}.photos{display:flex;gap:10px;flex-wrap:wrap}.photos img{width:180px;height:180px;object-fit:contain;border:1px solid #ddd;border-radius:8px}.itempics{display:flex;gap:5px;flex-wrap:wrap}.itempic{width:70px;height:70px;object-fit:cover;border-radius:6px}table{border-collapse:collapse;width:100%;margin-top:12px}th,td{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top}</style></head><body><h1>'+esc(title)+'</h1><p>Generated '+new Date().toLocaleString()+'</p>'+body+'</body></html>'}
async function exportCurrentCsv(){const its=current();if(!its.length)return alert('There are no items in the current order to export.');const rows=[['Item','Cigar / Item','Vitola / Size','Quantity','Original USD','Tax USD','Quantity Fee USD','Box Fee USD','Calculated Total EGP','Price / Stick EGP','USDT/EGP Rate','Rate Source','Item Picture URLs','Item Picture Filenames']];its.forEach((it,i)=>{const as=Array.isArray(it.alloc)&&it.alloc.length?it.alloc:[{name:it.cigar||it.label||'',vitola:it.vitola||'',qty:it.q,price:it.per,image_urls:[]}];as.forEach(a=>{const urls=imgUrls(a);const files=Array.isArray(a._imageFiles)?a._imageFiles:(a._imageFile?[a._imageFile]:[]);rows.push([i+1,a.name||it.cigar||it.label||'',a.vitola||it.vitola||'',num(a.qty||it.q),money(it.p),money(it.tax),money(it.f),money(it.b),money(it.total),money(a.price??it.per),num(it.rate).toFixed(2),it.rateSource==='manual'?'Manual':'Live',urls.join(' | '),files.map(f=>f.name).join(' | ')])})});rows.push([]);rows.push(['Actual amount paid EGP',document.getElementById('actualPaid')?.value||'','Supplier',document.getElementById('orderSupplier')?.value||'','Delivery USD',document.getElementById('orderDelivery')?.value||0,'Other fees USD',document.getElementById('orderOtherFees')?.value||0]);rows.push(['Whole order picture files',Array.from(document.getElementById('orderPicture')?.files||[]).map(f=>f.name).join(' | ')]);dl('cigar-current-order-'+stamp()+'.csv',csv(rows),'text/csv;charset=utf-8')}
async function exportInventoryCsv(){const os=orders();if(!os.length)return alert('There is no inventory purchase history to export yet.');const rows=[['Purchase Date','Order ID','Supplier','Cigar / Item','Vitola / Size','Quantity','Price / Stick EGP','Calculated Order EGP','Actual Paid EGP','Delivery USD','Other Fees USD','USDT/EGP Rate','Rate Source','Allocation Mode','Item Picture URLs','Whole Order Picture URLs']];os.forEach(o=>itemRows(o).forEach(x=>rows.push([o.created_at||o.date||'',o.id||'',o.supplier||'',itemName(x),x.vitola_snapshot||x.vitola||'',itemQty(x),money(itemPrice(x)),money(o.calculated_total_egp??o.total_egp??0),money(o.actual_total_egp??o.total_egp??0),money(o.delivery_fee_usd),money(o.other_fees_usd),num(o.usdt_egp_rate||x.rate).toFixed(2),(o.rate_source||x.rateSource)==='manual'?'Manual':'Live',x.allocation_mode||'',imgUrls(x).join(' | '),orderPics(o).join(' | ')])));dl('cigar-inventory-history-'+stamp()+'.csv',csv(rows),'text/csv;charset=utf-8')}
async function exportCurrentHtml(){const its=current();if(!its.length)return alert('There are no items in the current order to export.');const files=Array.from($('orderPicture')?.files||[]);const allocToItems=it=>(Array.isArray(it.alloc)&&it.alloc.length?it.alloc:[{name:it.cigar||it.label||'',vitola:it.vitola||'',qty:it.q,price:it.per,image_urls:[]}]).map(a=>({cigar_name_snapshot:a.name,vitola_snapshot:a.vitola,quantity:a.qty,price_per_stick_egp:a.price,image_url:a.image_url||'',image_urls:Array.isArray(a.image_urls)?a.image_urls:[],_imageFiles:Array.isArray(a._imageFiles)?a._imageFiles:(a._imageFile?[a._imageFile]:[])}));const o={title:'Current Order',created_at:new Date().toISOString(),supplier:$('orderSupplier')?.value||'',actual_total_egp:$('actualPaid')?.value||'',order_image_urls:await Promise.all(files.map(fileData)),items:its.flatMap(allocToItems)};dl('cigar-current-order-'+stamp()+'.html',await makeReport('Cigar Current Order',x=>'Supplier: '+(x.supplier||'—')+' · Actual paid: '+(x.actual_total_egp||'—')+' EGP · '+new Date(x.created_at).toLocaleString(),[o]),'text/html;charset=utf-8')}
async function exportInventoryHtml(){const os=orders();if(!os.length)return alert('There is no inventory purchase history to export yet.');dl('cigar-inventory-history-'+stamp()+'.html',await makeReport('Cigar Inventory History',o=>'Supplier: '+(o.supplier||'—')+' · Actual paid: '+(o.actual_total_egp??o.total_egp??0)+' EGP · '+new Date(o.created_at||o.date).toLocaleString(),os),'text/html;charset=utf-8')}
function addButtons(){const tabs=document.querySelector('.tabs');if(!tabs||document.getElementById('exportOrderBtn'))return;const w=document.createElement('div');w.style.cssText='display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;margin:0 0 12px';w.innerHTML='<button class="btn" id="exportOrderBtn">↓ Order CSV</button><button class="btn" id="exportOrderPicturesBtn">↓ Order + Pictures</button><button class="btn" id="exportInventoryBtn">↓ Inventory CSV</button><button class="btn" id="exportInventoryPicturesBtn">↓ Inventory + Pictures</button>';tabs.parentNode.insertBefore(w,tabs.nextSibling);$('exportOrderBtn').onclick=exportCurrentCsv;$('exportOrderPicturesBtn').onclick=exportCurrentHtml;$('exportInventoryBtn').onclick=exportInventoryCsv;$('exportInventoryPicturesBtn').onclick=exportInventoryHtml}
window.exportCurrentOrderCsv=exportCurrentCsv;window.exportInventoryHistoryCsv=exportInventoryCsv;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButtons);else addButtons();
})();