'use strict';
(function(){
let client,user=null,orders=[],editOrder=null,draft=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const egp=x=>Number(x||0).toLocaleString(undefined,{maximumFractionDigits:2})+' EGP';
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
async function initClient(){const t=await fetch('app.js',{cache:'no-store'}).then(r=>r.text());const url=(t.match(/SUPABASE_URL\s*=\s*['\"]([^'\"]+)/)||[])[1],key=(t.match(/SUPABASE_KEY\s*=\s*['\"]([^'\"]+)/)||[])[1];if(!url||!key)throw new Error('Could not initialize cloud database');client=window.supabase.createClient(url,key)}
function ensureModal(){if(document.getElementById('orderEditModal'))return;const m=document.createElement('div');m.id='orderEditModal';m.className='modal hidden';m.innerHTML=`<div class="modalBackdrop" data-close-order></div><div class="modalCard"><div class="modalHead"><div><h2 id="orderEditTitle">Edit order</h2><div id="orderEditSub" class="muted"></div></div><button class="btn" data-close-order>×</button></div><div id="orderEditRate" class="history"></div><div id="orderEditRows" style="margin-top:12px"></div><div class="actions" style="justify-content:space-between"><button class="btn" id="orderAddLine">＋ Add item</button><div style="display:flex;gap:8px"><button class="btn" data-close-order>Cancel</button><button class="btn primary" id="orderSaveEdit">Save changes</button></div></div><div id="orderEditMsg" class="note"></div></div>`;document.body.appendChild(m);m.querySelectorAll('[data-close-order]').forEach(b=>b.onclick=close);document.getElementById('orderAddLine').onclick=()=>{draft.push({id:null,name:'',vitola:'',quantity:1,price:0,mode:'manual'});renderRows()};document.getElementById('orderSaveEdit').onclick=save}
function close(){const m=document.getElementById('orderEditModal');if(m)m.classList.add('hidden');editOrder=null;draft=[]}
function renderRows(){const el=document.getElementById('orderEditRows');el.innerHTML=draft.map((x,i)=>`<div class="allocItem" style="grid-template-columns:1.5fr 150px 90px 160px auto"><div><label>Cigar / item</label><input data-k="name" data-i="${i}" value="${esc(x.name)}" placeholder="Cigar name"></div><div><label>Vitola / size</label><input data-k="vitola" data-i="${i}" value="${esc(x.vitola)}" placeholder="Robusto"></div><div><label>Qty</label><input type="number" min="1" data-k="quantity" data-i="${i}" value="${x.quantity}"></div><div><label>Price / stick EGP</label><input type="number" min="0" step=".01" data-k="price" data-i="${i}" value="${x.price}"></div><button class="btn del" data-remove="${i}" type="button">×</button></div>`).join('');el.querySelectorAll('input').forEach(inp=>inp.oninput=()=>{const i=+inp.dataset.i,k=inp.dataset.k;draft[i][k]=(k==='name'||k==='vitola')?inp.value:(+inp.value||0);updateTotals()});el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{draft.splice(+b.dataset.remove,1);renderRows()});updateTotals()}
function updateTotals(){const q=draft.reduce((s,x)=>s+(+x.quantity||0),0),t=draft.reduce((s,x)=>s+(+x.quantity||0)*(+x.price||0),0);const e=document.getElementById('orderEditSub');if(e)e.textContent=`${q} cigars · recalculated total ${egp(t)}`}
function open(o){ensureModal();editOrder=o;draft=(o.items||[]).map(x=>({id:x.id,name:x.cigar_name_snapshot||'',vitola:x.vitola_snapshot||'',quantity:+x.quantity||1,price:+x.price_per_stick_egp||0,mode:x.allocation_mode||'manual'}));document.getElementById('orderEditTitle').textContent=`Edit Order ${o.displayNumber}`;document.getElementById('orderEditRate').innerHTML=`<b>USDT/EGP: ${Number(o.usdt_egp_rate||0).toFixed(2)}</b> · ${o.rate_source==='manual'?'Manual rate':'Live rate'}<div class="muted" style="margin-top:4px">Changing quantity or price/stick recalculates the order total. The original USDT/EGP rate is preserved.</div>`;document.getElementById('orderEditMsg').textContent='';renderRows();document.getElementById('orderEditModal').classList.remove('hidden')}
async function load(){const s=await client.auth.getSession();user=s.data.session?.user||null;if(!user)return;const [or,ir]=await Promise.all([client.from('orders').select('*').order('created_at',{ascending:false}),client.from('order_items').select('*').order('created_at')]);if(or.error||ir.error){console.error(or.error||ir.error);return}orders=(or.data||[]).map((o,i)=>({...o,displayNumber:(or.data||[]).length-i,items:(ir.data||[]).filter(x=>x.order_id===o.id)}));render()}
function render(){const el=document.getElementById('hist');if(!el)return;if(!orders.length){el.innerHTML='<div class="muted" style="padding:20px;text-align:center">No saved orders yet.</div>';return}el.innerHTML=orders.map(o=>`<div class="historyCard"><div class="historyHead"><div><b>Order ${o.displayNumber}</b><div class="pill">${new Date(o.created_at).toLocaleString()} · ${o.total_cigars} cigars</div></div><b>${egp(o.total_egp)}</b></div><div class="meta" style="margin-top:8px"><b>USDT/EGP rate: ${Number(o.usdt_egp_rate||0).toFixed(2)} EGP/USDT</b> · ${o.rate_source==='manual'?'Manual rate':'Live rate'}<br>${o.items.map(x=>`${esc(x.cigar_name_snapshot)}${x.vitola_snapshot?' · '+esc(x.vitola_snapshot):''} — ${x.quantity} × ${egp(x.price_per_stick_egp)}`).join('<br>')}</div><div class="buttons"><button class="btn small" data-edit="${o.id}">Edit order</button><button class="btn small del" data-delete="${o.id}">Delete order</button></div></div>`).join('');el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(orders.find(o=>o.id===b.dataset.edit)));el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteOrder(b.dataset.delete))}
async function getCigar(name,vitola){const key=norm(name)+'|'+norm(vitola);let r=await client.from('cigars').select('*').eq('user_id',user.id).eq('normalized_key',key).maybeSingle();if(r.error)throw r.error;if(r.data)return r.data;r=await client.from('cigars').insert({user_id:user.id,name,normalized_name:norm(name),normalized_key:key,vitola:vitola||''}).select().single();if(r.error)throw r.error;return r.data}
async function save(){const msg=document.getElementById('orderEditMsg');msg.textContent='Saving…';try{draft=draft.filter(x=>String(x.name||'').trim());if(!draft.length){if(!confirm('Remove all items and delete this order?')){msg.textContent='Cancelled.';return}for(const table of ['cigar_price_history','order_items']){const r=await client.from(table).delete().eq('order_id',editOrder.id);if(r.error)throw r.error}let r=await client.from('orders').delete().eq('id',editOrder.id);if(r.error)throw r.error;close();return load()}for(const x of draft){if(+x.quantity<1)throw new Error('Every item needs a quantity of at least 1.');if(+x.price<0)throw new Error('Price/stick cannot be negative.')}const q=draft.reduce((s,x)=>s+(+x.quantity||0),0),total=draft.reduce((s,x)=>s+(+x.quantity||0)*(+x.price||0),0);for(const x of draft)x.cigar=await getCigar(String(x.name).trim(),String(x.vitola||'').trim());const ids=draft.filter(x=>x.id).map(x=>x.id),old=(editOrder.items||[]).map(x=>x.id),removed=old.filter(id=>!ids.includes(id));if(removed.length){const r=await client.from('order_items').delete().in('id',removed);if(r.error)throw r.error}for(const x of draft){const p={cigar_id:x.cigar.id,cigar_name_snapshot:String(x.name).trim(),vitola_snapshot:String(x.vitola||'').trim(),quantity:+x.quantity,price_per_stick_egp:+x.price,allocation_mode:x.mode||'manual'};const r=x.id?await client.from('order_items').update(p).eq('id',x.id):await client.from('order_items').insert({...p,order_id:editOrder.id,user_id:user.id});if(r.error)throw r.error}let r=await client.from('cigar_price_history').delete().eq('order_id',editOrder.id);if(r.error)throw r.error;const ir=await client.from('order_items').select('*').eq('order_id',editOrder.id);if(ir.error)throw ir.error;r=await client.from('orders').update({total_cigars:q,total_egp:total,average_per_stick_egp:q?total/q:0}).eq('id',editOrder.id);if(r.error)throw r.error;const hist=(ir.data||[]).map(x=>({user_id:user.id,cigar_id:x.cigar_id,order_id:editOrder.id,purchased_at:editOrder.created_at,quantity:x.quantity,price_per_stick_egp:x.price_per_stick_egp,order_total_egp:total,usdt_egp_rate:editOrder.usdt_egp_rate,rate_source:editOrder.rate_source,vitola_snapshot:x.vitola_snapshot||''}));if(hist.length){r=await client.from('cigar_price_history').insert(hist);if(r.error)throw r.error}close();await load()}catch(e){console.error(e);msg.textContent='Could not save changes: '+(e.message||e)}}
async function deleteOrder(id){if(!confirm('Delete this entire order and its purchase history? This cannot be undone.'))return;try{for(const table of ['cigar_price_history','order_items']){const r=await client.from(table).delete().eq('order_id',id);if(r.error)throw r.error}const r=await client.from('orders').delete().eq('id',id);if(r.error)throw r.error;await load()}catch(e){alert('Could not delete order: '+(e.message||e))}}
async function start(){ensureModal();try{await initClient()}catch(e){console.error(e);return}client.auth.onAuthStateChange((e,s)=>{user=s?.user||null;if(user)setTimeout(load,100)});setTimeout(load,900);const tab=document.getElementById('historyTab');if(tab)tab.addEventListener('click',()=>setTimeout(load,100))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
